# For postgresql, type:
# createdb radiator_development 

development:
  adapter: postgresql
  database: radiator_development
  username: radiator
  password: radiator
  host: localhost

test:
  adapter: postgresql
  database: radiator_test
  username: radiator
  password: radiator
  host: localhost

production:
  adapter: postgresql
  database: radiator_production
  username: radiator
  password: radiator
  host: localhost
